name: Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - run: pip install pip==22.0.4
    - run: pip install nox==2022.1.7
    - run: pip install poetry==1.1.13
    - run: pip install nox-poetry==0.9.0
    - run: nox
