name: Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  tests:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - run: python -m pip install pip==22.0.3
    - run: python -m pip install nox==2022.1.7
    - run: python -m pip install poetry==1.1.13
    - run: python -m pip install nox-poetry==0.9.0
    - run: nox
